### ISSUE TITLE
Top Salary Request Filtered to CS Classification

### ISSUE THREAD

**Issue by JamesLeGres** [dougkeefe/ps-salary-data#11]
When I query https://ps-salary-data.vercel.app/api/top - Only the 5x CS classifications are available. Thanks a lot for this Doug - another small suggestion would be to include in the description some sense of how you pull the data/and confidence whether this can be relied upon for continual updates.

Cheers from DND

**Comment by dougkeefe** [comment]
Thanks for catching that!  Will get that one fixed. 

And a great suggestion on adding how it was collected too.  All scraped from the website. In an ideal world we would have it accessible as a dataset from something like open.Canada.ca but after going through it myself I can understand how having a 100% complete set would be difficult to obtain within a single data model. 

There are a lot of complexities around the edges of classifications. 

Can definitely be achieved but will break the simplicity of this MVP. 

Really appreciate the comments
